/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fluffycontrol;


import java.awt.*;

/**
 * Date: 2026-06-29
 * @author OwO
 */
public class menuJPanel extends javax.swing.JPanel {    
    /**
     * Creates new form menuJPanel
     */
    public menuJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rngGameButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        rngGameButton.setBackground(new java.awt.Color(214, 214, 255));
        rngGameButton.setFont(new java.awt.Font("Verdana", Font.BOLD, 15)); // NOI18N
        rngGameButton.setText("RNG Game");
        rngGameButton.setToolTipText("");
        rngGameButton.addActionListener(this::rngGameButtonActionPerformed);

        jLabel1.setFont(new java.awt.Font("Verdana", Font.BOLD, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(214, 214, 255));
        jLabel1.setText("Fluffy Control :3");

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(214, 214, 255));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Verdana", Font.BOLD, 15)); // NOI18N
        textArea.setRows(5);
        textArea.setText("Output");
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(rngGameButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(rngGameButton)
                .addGap(139, 139, 139)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rngGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rngGameButtonActionPerformed
       String text = MainFrame.GUILinker("rngGame");
       textArea.setText(text); 
    }//GEN-LAST:event_rngGameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rngGameButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
